security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: true

            json_login:
                check_path: app_api_login

            custom_authenticator: App\Security\ApiTokenAuthenticator

    access_control:
        # Routes publiques
        - { path: ^/api/registration$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/login$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }

        # CARTE PUBLIQUE
        - { path: ^/api/categories$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/categories/[0-9]+$, roles: PUBLIC_ACCESS, methods: [GET] }

        - { path: ^/api/foods$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/foods/[0-9]+$, roles: PUBLIC_ACCESS, methods: [GET] }

        - { path: ^/api/menus$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/menus/[0-9]+$, roles: PUBLIC_ACCESS, methods: [GET] }

        - { path: ^/api/bookings/availability$, roles: PUBLIC_ACCESS, methods: [GET] }

        - { path: ^/api/restaurants/[0-9]+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/restaurants/[0-9]+/pictures$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/restaurants/[0-9]+/pictures/[0-9]+$, roles: PUBLIC_ACCESS, methods: [GET] }

        
        # ADMINISTRATION DE LA CARTE
        - { path: ^/api/categories, roles: ROLE_ADMIN, methods: [POST, PUT, PATCH, DELETE] }
        - { path: ^/api/foods, roles: ROLE_ADMIN, methods: [POST, PUT, PATCH, DELETE] }
        - { path: ^/api/menus, roles: ROLE_ADMIN, methods: [POST, PUT, PATCH, DELETE] }

        # Administration du restaurant : administrateur uniquement.
        - { path: ^/api/restaurants, roles: ROLE_ADMIN, methods: [POST, PUT, PATCH, DELETE] }

        # Toutes les autres routes API nécessitent une authentification.
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
